# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[mgr]
ratio          = [ 2, 4, 3 ]  # widen preview pane
linemode       = "mtime"
mouse_events   = [ "click", "scroll", "touch", "move", "drag"]

[preview]
image_quality  = 90
image_filter    = "lanczos3"

[plugin]
prepend_previewers = [
  { url = "*.{png,jpg,jpeg,jpe,gif,webp,bmp,avif,heic,heif,svg}", run = "image" },
  { mime = "image/*", run = "image" },
  { url = "*.pdf", run = 'piper -- pdftotext -layout %s1 -' },
  { url = "*.{tar,tar.gz,tgz,zip,7z,rar}", run = 'piper -- bsdtar -tf %s1' },
  { url = "*.md", run = "glow" },
  { url = "*", run = "rich-preview" },
]

[opener]
edit = [
  { run = 'nvim %s', block = true, desc = "Edit with nvim", for = "unix" },
]
view = [
  { run = 'bat --paging=always --style=numbers --color=always %s', block = true, desc = "View with bat", for = "unix" },
  { run = 'less -R %s', block = true, desc = "View with less (fallback)", for = "unix" },
]
extract = [
  { run = 'bsdtar -xvf %s1', block = true, desc = "Extract archive here", for = "unix" },
]
compress = [
  { run = 'tar -cvzf %s1.tar.gz %s1', block = true, desc = "Compress to tar.gz", for = "unix" },
]

[open]
rules = [
  { url = "*", use = "edit" },
]

[terminal]
emulator = "/usr/bin/kitty"