#!/bin/sh
vol=$(pactl get-sink-volume @DEFAULT_SINK@ 2>/dev/null | awk 'NR==1{print $5}')
muted=$(pactl get-sink-mute @DEFAULT_SINK@ 2>/dev/null | awk '{print $2}')

if [ "$muted" = "yes" ]; then
    echo "^c#ff3333^VOL^c#ffffff^MUTE^d^"
else
    echo "^c#00ffff^VOL^c#ffffff^${vol}^d^"
fi
