return {
	{
		"petertriho/nvim-scrollbar",
		event = "VeryLazy",
		dependencies = {
			"kevinhwang91/nvim-hlslens",
		},
		opts = {
			show = true,
			show_in_active_only = false,
			set_highlights = true,
			faded_on_inactive = true,
			handle = {
				text = " ",
				blend = 30,
				color = "#89B4FA",
				color_nr = nil,
				highlight = "CursorColumn",
				hide_if_all_visible = true,
			},
			marks = {
				Cursor = {
					text = "•",
					priority = 0,
					gui = nil,
					color = "#F38BA8",
					cterm = nil,
					color_nr = nil,
					highlight = "Normal",
				},
				Search = {
					text = { "-", "=" },
					priority = 1,
					gui = nil,
					color = "#FAB387",
					cterm = nil,
					color_nr = nil,
					highlight = "Search",
				},
				Error = {
					text = { "-", "=" },
					priority = 2,
					gui = nil,
					color = "#F38BA8",
					cterm = nil,
					color_nr = nil,
					highlight = "DiagnosticVirtualTextError",
				},
				Warn = {
					text = { "-", "=" },
					priority = 3,
					gui = nil,
					color = "#F9E2AF",
					cterm = nil,
					color_nr = nil,
					highlight = "DiagnosticVirtualTextWarn",
				},
				Info = {
					text = { "-", "=" },
					priority = 4,
					gui = nil,
					color = "#89B4FA",
					cterm = nil,
					color_nr = nil,
					highlight = "DiagnosticVirtualTextInfo",
				},
				Hint = {
					text = { "-", "=" },
					priority = 5,
					gui = nil,
					color = "#94E2D5",
					cterm = nil,
					color_nr = nil,
					highlight = "DiagnosticVirtualTextHint",
				},
				Misc = {
					text = { "-", "=" },
					priority = 6,
					gui = nil,
					color = "#CBA6F7",
					cterm = nil,
					color_nr = nil,
					highlight = "Normal",
				},
				GitAdd = {
					text = "┆",
					priority = 7,
					gui = nil,
					color = "#A6E3A1",
					cterm = nil,
					color_nr = nil,
					highlight = "GitSignsAdd",
				},
				GitChange = {
					text = "┆",
					priority = 7,
					gui = nil,
					color = "#FAB387",
					cterm = nil,
					color_nr = nil,
					highlight = "GitSignsChange",
				},
				GitDelete = {
					text = "▁",
					priority = 7,
					gui = nil,
					color = "#F38BA8",
					cterm = nil,
					color_nr = nil,
					highlight = "GitSignsDelete",
				},
			},
			excluded_buftypes = {
				"terminal",
			},
			excluded_filetypes = {
				"cmp_docs",
				"cmp_menu",
				"noice",
				"prompt",
				"TelescopePrompt",
				"nvdash",
			},
			autocmd = {
				render = {
					"BufWinEnter",
					"TabEnter",
					"TermEnter",
					"WinEnter",
					"CmdwinLeave",
					"TextChanged",
					"VimResized",
					"WinScrolled",
				},
				clear = {
					"BufWinLeave",
					"TabLeave",
					"TermLeave",
					"WinLeave",
				},
			},
			handlers = {
				cursor = true,
				diagnostic = true,
				gitsigns = true,
				handle = true,
				search = true,
				ale = false,
			},
		},
		config = function(_, opts)
			require("scrollbar").setup(opts)
			require("scrollbar.handlers.gitsigns").setup()
			require("scrollbar.handlers.search").setup()
		end,
	},
	{
		"kevinhwang91/nvim-hlslens",
		event = "VeryLazy",
		opts = {
			calm_down = true,
			nearest_only = true,
			nearest_float_when = "always",
		},
	},
}
